# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z1dJigkHAV2hEFSqB_iVryJlrSVxjZ2d
"""

import numpy as np

import pandas as pd

car=pd.read_csv('car.csv')

car.head()

car['selling_price']> 500000

car[car['selling_price']> 500000]

car[car['selling_price']> 1000000]

car['year']>2018

car[car['year']>2018
  ]

car[car['year']>2019]

car['km_driven']<2000

car[car['km_driven']<2000]

car[car['km_driven']<1000]

from matplotlib import pyplot as plt

import seaborn as sns

sns.scatterplot(x='selling_price',y='km_driven',data=car)
plt.show

sns.scatterplot(x='year',y='km_driven',data=car)
plt.show

sns.scatterplot(x='km_driven',y='year',data=car)
plt.show

sns.scatterplot(x='km_driven',y='year',data=car,hue='fuel')
plt.show

sns.scatterplot(x='year',y='km_driven',data=car,hue='fuel')
plt.show

car.head()

y=car[['selling_price']]

x=car[['km_driven']]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

x_train.head()

x_test.head()

y_train.head()

y_test.head()

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)

lr.predict(x_test)

y_pred=lr.predict(x_test)

y_test.head()

y_pred[0:5]

from sklearn.metrics import mean_squared_error

mean_squared_error(y_test,y_pred)

#model 2

car.head()

y=car[['selling_price']]

x=car[['km_driven','year']]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

lr2=LinearRegression()

lr2.fit(x_train,y_train)

y_pred=lr2.predict(x_test)

mean_squared_error(y_test,y_pred)

