# -*- coding: utf-8 -*-
"""car data set Linear regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TC3yZG83i_zxdTk2V3-cqdbvYY96dnS_
"""

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('/content/drive/MyDrive/CAR DETAILS FROM CAR DEKHO csv.csv')

data.head()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data.name=le.fit_transform(data.name)
data.fuel=le.fit_transform(data.fuel)
data.seller_type=le.fit_transform(data.seller_type)
data.transmission=le.fit_transform(data.transmission)
data.owner=le.fit_transform(data.owner)

data.head()

data.tail()

data.describe()

data.info()

data.corr()

data.columns

y=data['selling_price']
x=data[['name', 'year', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner']]

sns.pairplot(data)

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

x_train.head()

x_test.head()

y_train.head()

y_test.head()

from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(x,y)

model.intercept_

model.coef_